name: El alien toca botón
attire:
  active: El alien toca botón
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  defaultToolbox: |
  defaultToolbox: |
      <category name="Comandos primitivos">
        <block type="MoverAlienAlEste"></block>
        <block type="TocarBotón"></block>
      </category>
      <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
      <category name="Definiciones">
        <block type="procedures_defnoreturnnoparams"></block>
      </category>
board:
  active: 1
  initial_board_source: selected
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: true
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
